version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: docker/production/nginx.Dockerfile
    restart: always
    depends_on: 
      - app
    ports:
      - "80:80"
    networks:
      - morgado

  app:
    restart: always
    env_file: docker/production/.env
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/app
    # ports:
    #   - "80:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  
  db:
    image: postgres:12.3
    env_file: docker/production/.env
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks: 
      - morgado

volumes:
  postgres-data:

networks:
  morgado:

